const cities = [
	{ code: 'mke', city: 'Milwaukee', state: 'WI' },
	{ code: 'abq', city: 'Albuquerque', state: 'NM' },
	{ code: 'abe', city: 'Allentown', state: 'PA' },
	{ code: 'atl', city: 'Atlanta', state: 'GA' },
	{ code: 'aus', city: 'Austin', state: 'TX' },
	{ code: 'bwi', city: 'Baltimore', state: 'MD' },
	{ code: 'bhm', city: 'Birmingham', state: 'AL' },
	{ code: 'bos', city: 'Boston', state: 'MA' },
	{ code: 'buf', city: 'Buffalo', state: 'NY' },
	{ code: 'clt', city: 'Charlotte', state: 'NC' },
	{ code: 'ord', city: 'Chicago', state: 'IL' },
	{ code: 'cvg', city: 'Cincinatti', state: 'OH' },
	{ code: 'cle', city: 'Cleveland', state: 'OH' },
	{ code: 'cae', city: 'Columbia', state: 'OH' },
	{ code: 'dfw', city: 'Dallas', state: 'TX' },
	{ code: 'day', city: 'Dayton', state: 'OH' },
	{ code: 'den', city: 'Denver', state: 'CO' },
	{ code: 'dtw', city: 'Detroit', state: 'MI' },
	{ code: 'fmy', city: 'Fort Myers', state: 'FL' },
	{ code: 'grb', city: 'Green Bay', state: 'WI' },
	{ code: 'gso', city: 'Greensboro', state: 'TX' },
	{ code: 'bdl', city: 'Hartford', state: 'CT' },
	{ code: 'cxy', city: 'Harrisburg', state: 'PA' },
	{ code: 'hsv', city: 'Hunstville', state: 'AL' },
	{ code: 'iah', city: 'Houston', state: 'TX' },
	{ code: 'ind', city: 'Indianapolis', state: 'IN' },
	{ code: 'jax', city: 'Jacksonville', state: 'FL' },
	{ code: 'mci', city: 'Kansas City', state: 'MO' },
	{ code: 'las', city: 'Las Vegas', state: 'NV' },
	{ code: 'lit', city: 'Little Rock', state: 'AK' },
	{ code: 'vny', city: 'Los Angeles', state: 'CA' },
	{ code: 'lou', city: 'Louisville', state: 'KY' },
	{ code: 'mem', city: 'Memphis', state: 'TN' },
	{ code: 'mia', city: 'Miami', state: 'FL' },
	{ code: 'pou', city: 'Middletown', state: 'NJ' },
	{ code: 'msp', city: 'Minneapolis', state: 'MN' },
	{ code: 'mob', city: 'Mobile', state: 'AL' },
	{ code: 'bna', city: 'Nashville', state: 'TN' },
	{ code: 'msy', city: 'New Orleans', state: 'LA' },
	{ code: 'nyc', city: 'New York', state: 'NY' },
	{ code: 'orf', city: 'Norfolk', state: 'VA' },
	{ code: 'okc', city: 'Oklahoma City', state: 'OK' },
	{ code: 'oma', city: 'Omaha', state: 'NB' },
	{ code: 'mco', city: 'Orlando', state: 'FL' },
	{ code: 'phl', city: 'Philidelphia', state: 'PA' },
	{ code: 'phx', city: 'Phoenix', state: 'AZ' },
	{ code: 'pit', city: 'Pittsburgh', state: 'PA' },
	{ code: 'pwm', city: 'Portland', state: 'ME' },
	{ code: 'pdx', city: 'Portland', state: 'OR' },
	{ code: 'pvd', city: 'Providence', state: 'RI' },
	{ code: 'rdu', city: 'Raleigh', state: 'NC' },
	{ code: 'ric', city: 'Richmond', state: 'VA' },
	{ code: 'roc', city: 'Rochester', state: 'NY' },
	{ code: 'sac', city: 'Sacramento', state: 'CA' },
	{ code: 'mbs', city: 'Saginaw', state: 'MI' },
	{ code: 'slc', city: 'Salt Lake City', state: 'UT' },
	{ code: 'sat', city: 'San Antonio', state: 'TX' },
	{ code: 'san', city: 'San Diego', state: 'CA' },
	{ code: 'sfo', city: 'San Francisco', state: 'CA' },
	{ code: 'avp', city: 'Scranton', state: 'OH' },
	{ code: 'sea', city: 'Seattle', state: 'WA' },
	{ code: 'stl', city: 'St Louis', state: 'MO' },
	{ code: 'unv', city: 'State College', state: 'PA' },
	{ code: 'sgf', city: 'Springfield', state: 'IL' },
	{ code: 'tlh', city: 'Tallahassee', state: 'FL' },
	{ code: 'tpa', city: 'Tampa', state: 'FL' },
	{ code: 'top', city: 'Topeka', state: 'KS' },
	{ code: 'ttn', city: 'Trenton', state: 'NJ' },
	{ code: 'dca', city: 'Washington', state: 'DC' }
]